// Generated by Gemini

using UnityEngine;
using UnityEngine.UIElements;

public class DragManipulator : PointerManipulator
{
    private Vector2 _startMousePosition;
    private Vector2 _startElementPosition;
    private bool _isActive;
    private readonly VisualElement _targetWindow;

    /// <param name="targetWindow">The actual element that will be moved (e.g., the dialog panel).</param>
    public DragManipulator(VisualElement targetWindow)
    {
        _targetWindow = targetWindow;
    }

    protected override void RegisterCallbacksOnTarget()
    {
        // 'target' is the element this manipulator is attached to (e.g., the title bar)
        target.RegisterCallback<PointerDownEvent>(OnPointerDown);
        target.RegisterCallback<PointerMoveEvent>(OnPointerMove);
        target.RegisterCallback<PointerUpEvent>(OnPointerUp);
    }

    protected override void UnregisterCallbacksFromTarget()
    {
        target.UnregisterCallback<PointerDownEvent>(OnPointerDown);
        target.UnregisterCallback<PointerMoveEvent>(OnPointerMove);
        target.UnregisterCallback<PointerUpEvent>(OnPointerUp);
    }

    private void OnPointerDown(PointerDownEvent evt)
    {
        if (_targetWindow == null) return;

        // Record the initial mouse position
        _startMousePosition = evt.position;

        // Record the initial position of the window relative to its parent
        // Ensure the targetWindow has 'position: absolute' in USS
        _startElementPosition = new Vector2(
            _targetWindow.resolvedStyle.left, 
            _targetWindow.resolvedStyle.top
        );
        
        _isActive = true;

        // Capture the pointer to receive events even if the cursor leaves the title bar area
        target.CapturePointer(evt.pointerId);
        
        // Prevent the event from triggering other UI elements underneath
        evt.StopPropagation();
    }

    private void OnPointerMove(PointerMoveEvent evt)
    {
        if (!_isActive || !target.HasPointerCapture(evt.pointerId)) return;

        // Calculate how much the mouse has moved since the click
        Vector2 delta = (Vector2)evt.position - _startMousePosition;

        // Apply the delta to the initial element position
        _targetWindow.style.left = _startElementPosition.x + delta.x;
        _targetWindow.style.top = _startElementPosition.y + delta.y;
        
        evt.StopPropagation();
    }

    private void OnPointerUp(PointerUpEvent evt)
    {
        if (!_isActive || !target.HasPointerCapture(evt.pointerId)) return;

        _isActive = false;

        // Release the pointer capture once dragging is finished
        target.ReleasePointer(evt.pointerId);
        evt.StopPropagation();
    }
}

// // window: The main container you want to move
// // titleBar: The handle used for dragging
// var window = root.Q<VisualElement>("MyDialog");
// var titleBar = root.Q<VisualElement>("TitleBarHandle");

// // Attach the manipulator to the titleBar, but pass the window as the move target
// titleBar.AddManipulator(new DragManipulator(window));